### ISSUE TITLE
How to add init scripts or extend init process?

### ISSUE THREAD

**Issue by pwFoo** [u-root/u-root#569] opened 2018-01-23 21:42 UTC
Is it possible to extend u-root init process or add something like init.d scripts?
Haven't found documentation about.

**Comment by rminnich** [comment] 2018-01-23 22:23
we've had this discussion on slack.

This is the thinking so far:
- we don't want systemd
- we don't want init.d scripts
- we don't want upstart
- "scripts" need to be go programs so we can at least verify they don't contain dumb errors
- "scripts" also should be able to dynamically compile like any other u-root command if desired
- "scripts" should not be shell scripts, since we have no agreement on a shell yet

-services are written in Go, and are controllable via some sort of REST or gRPC interface
- it's 2018, and we don't have to restrict to stdin/stdout/signal to control things
- the service that manages the services is itself a service that follows these rules

we should consider systems like https://github.com/hashicorp/go-plugin

**Comment by rminnich** [comment] 2018-01-23 22:24
Oh and thanks for making this issue.

**Comment by pwFoo** [comment] 2018-01-24 05:56
@rminnich 
At the moment I play around with a custom (shell) init script. Maybe I can convert it to go (mount cgroups, prepare some things, ...) in the future.

init.d was just a known example. I dont won't to use systemd, upstart, sysvinit, ...
That's why I play around with custom init, busybox, linuxkit and u-root ;)

I just need a way to execute a script (I hope it could be go soon...) after system was bootet. :)

**Comment by pwFoo** [comment] 2018-01-25 07:50
@rminnich
Is it possible to execute a (Go) script after boot finished instead of just start a shell?

**Comment by hugelgupf** [comment] 2018-01-25 08:51
Yes. Include any Go command named uinit.

**Comment by pwFoo** [comment] 2018-01-25 09:04
Thanks! I'll convert my shell script to go and try it :)

**Comment by bensallen** [comment] 2018-02-03 15:47
Also see #60 to track the work around what @rminnich describes.

**Comment by rjoleary** [comment] 2018-07-15 05:28
The two relevant features here are:

* uinit (user init): any command named `uinit` will execute on startup
* SoS: Service of Services for daemons such as wifi

The rest is a duplicate of #60

**Comment by rjoleary** [comment] 2018-07-15 05:29
this is a duplicate of #60

**Closed by rjoleary** 2018-07-15 05:29 UTC

**Comment by pwFoo** [comment] 2018-07-15 05:42
@rjoleary
Is SoS documentation / example available?

**Comment by rjoleary** [comment] 2018-07-15 06:35
Documentation: https://godoc.org/github.com/u-root/u-root/pkg/sos (The documentation is limited at the moment; hopefully, this can be improved. Just filed #809. ) SoS is not about init scripts, rather it manages services.

Examples:

* wifi: https://github.com/u-root/u-root/blob/master/cmds/wifi/server.go
* upspin: https://github.com/u-root/u-root/blob/master/cmds/upspin_sos/server.go

@jbeta51 and @TrevorFarrelly are working on another service -- they know a lot more about SoS.
