### ISSUE TITLE
dhclient: resolv.conf race.

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#631] opened 2018-02-14 22:07 UTC
In its current state, dhclient will write out IPv4 DNS information and IPv6 DNS information separately. It does not append them to resolv.conf, it overwrites the whole file. Depending on what finishes last, the file will be either IPv4 or IPv6, or in the worst case, a fun mix of the two.

**Comment by rjoleary** [comment] 2021-05-27 07:45
Duplicate of 631

**Closed** 2021-05-27 07:46 UTC
