### ISSUE TITLE
Investigate strange coverage numbers

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#531] opened 2017-12-26 08:33 UTC
go test -cover does not seem to collect coverage on everything we want. E.g. take

go test -cover ./cmds/wget

which gives 0%, yet there is a test there that covers a bunch of stuff.

Someone should investigate how go test -cover gets its coverage numbers and fix our usage of it or fix go test -cover.

**Comment by hugelgupf** [comment] 2017-12-26 08:34
I'm gonna guess it has something to do with the `testutil` package.

**Comment by hugelgupf** [comment] 2017-12-26 08:34
@prattmic you deal with coverage all the time, if you have 5 mins can you take a guess and tell us what's wrong?

**Comment by rjoleary** [comment] 2017-12-26 10:14
Happy boxing day!

Is this a duplicate of https://github.com/u-root/u-root/issues/116 ?

If it is, our tools are not smart enough to fix it.

**Comment by prattmic** [comment] 2017-12-26 15:49
This is definitely a dup of #116.

**Closed by prattmic** 2017-12-26 15:49 UTC
